{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-tango-server
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - LimaCCDs = Lima.Server.LimaCCDs:main
    - LimaViewer = Lima.Server.LimaViewer:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - lima-core
    - pytango
    - pillow # Required by the Bpm plugin
    - pyturbojpeg # Required by the Bpm plugin
    - pymemcache # Required by the Memcached plugin
    - bloscpack # Required by the Memcached plugin

test:
  source_files:
    - tests
  requires:
    - pytest
    - fabio
  imports:
    - Lima.Server
  commands:
    - pytest tests

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: A library for the unified control of 2D detectors
