{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-tango-server
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  script: "pip install . -vv"
  entry_points:
    - LimaCCDs = Lima.Server.LimaCCDs:main
    - LimaViewer = Lima.Server.LimaViewer:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - pytango
    - pillow # Required by the Bpm plugin
    - pyturbojpeg # Required by the Bpm plugin
    - pymemcache # Required by the Memcached plugin
    - bloscpack # Required by the Memcached plugin

test:
  imports:
    - Lima.Server

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: A library for the unified control of 2D detectors
