{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: lima-tango-server
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  entry_points:
    - LimaCCDs = Lima.Server.LimaCCDs:main
    - LimaViewer = Lima.Server.LimaViewer:main

requirements:
  run:
    - pytango
    - pillow # Required by the Bpm plugin
    - libjpeg-turbo # Required by the Bpm plugin
    - pymemcache # Required by the Memcached plugin
    - bloscpack # Required by the Memcached plugin

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
